name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
          registry: registry-1-stage.docker.io
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          driver-opts: |
            internal.auth.host=https://auth-stage.docker.io
            internal.auth.entry=registry-1-stage.docker.io
            internal.address=tcp://build-cloud-stage.docker.com:443
            internal.hub.host=https://hub-stage.docker.com
          endpoint: "docker/hydrobuildtest"
          install: true
      - name: Build and push
        uses: ./.github/actions/docker-build-push-action
        with:
          tags: "registry-1-stage.docker.io/${{ vars.DOCKER_USER }}/docker-build-cloud-demo:latest"
          push: true
